kofu:
  message: hello
  item: item
  mail:
    base-url: http://127.0.0.1:8080
    from: kofu-r2dbc-jwt@localhost
  security:
    authentication:
      jwt:
        secret: secret
        base64-secret: MjNlZmQzMzgwM2MzN2FmMGNhZTY3NDllMDJiODg2YWRlMmY0ZDUzMzg2ODI4MTgxNmIxNzQ1OGEzMmNmNjY2OTA3Nzk4MzRkNDUzZWFlMTljZjJmNDU5NDNjOWI3NjRhNDg3MGYzODhiYjVjZWU5MmNhMDA2MDU3ZjA2NjJhODE=
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
#  cors:
#    allowed-origins: '*'
#    allowed-methods: '*'
#    allowed-headers: '*'
#    exposed-headers: 'Authorization,Link,X-Total-Count'
#    allow-credentials: true
#    cors.max-age: 1800
